#!/usr/bin/env bash
# ============================================================
#  StockArena — Raspberry Pi / Debian / Ubuntu Installer
#  Usage:
#    bash install.sh
#    curl -fsSL https://raw.githubusercontent.com/Namoh21/StockMarketSimulator/main/install.sh | bash
# ============================================================
set -e

# ── Config ────────────────────────────────────────────────────────────────────
REPO_URL="https://github.com/Namoh21/StockMarketSimulator"
INSTALL_DIR="$HOME/StockMarketSimulator"
SERVICE_NAME="stockarena"
PORT=8081
NODE_MAJOR=20

# ── Colors ────────────────────────────────────────────────────────────────────
R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; C='\033[0;36m'; N='\033[0m'; BOLD='\033[1m'

info()    { echo -e "${B}[INFO]${N}  $*"; }
success() { echo -e "${G}[OK]${N}    $*"; }
warn()    { echo -e "${Y}[WARN]${N}  $*"; }
error()   { echo -e "${R}[ERROR]${N} $*" >&2; exit 1; }
step()    { echo -e "\n${BOLD}${C}▶ $*${N}"; }

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}"
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║      📈  StockArena Installer v1.0           ║"
echo "  ║      Stock Trading Simulation Game           ║"
echo "  ╚══════════════════════════════════════════════╝"
echo -e "${N}"

# ── OS check ─────────────────────────────────────────────────────────────────
step "Checking system"
if [[ "$OSTYPE" != "linux"* ]]; then
    error "This installer is for Linux / Raspberry Pi OS only."
fi
if ! command -v apt-get &>/dev/null; then
    error "apt-get not found. This installer requires a Debian/Ubuntu-based OS."
fi

ARCH=$(uname -m)
info "Architecture : $ARCH"
info "OS           : $(. /etc/os-release && echo "$PRETTY_NAME")"
info "User         : $USER"
info "Install dir  : $INSTALL_DIR"
info "Port         : $PORT"

# ── System update & base packages ────────────────────────────────────────────
step "Updating package lists"
sudo apt-get update -qq

step "Installing build tools & dependencies"
sudo apt-get install -y --no-install-recommends \
    build-essential \
    python3 \
    python3-pip \
    git \
    curl \
    ca-certificates \
    gnupg \
    openssl \
    2>/dev/null
success "Build tools installed"

# ── Node.js ───────────────────────────────────────────────────────────────────
step "Setting up Node.js ${NODE_MAJOR}.x"
if command -v node &>/dev/null; then
    CURRENT_NODE=$(node --version 2>/dev/null | sed 's/v//' | cut -d. -f1)
    if [[ "$CURRENT_NODE" -ge 18 ]]; then
        success "Node.js $(node --version) already installed — skipping"
    else
        warn "Node.js v${CURRENT_NODE} is too old (need 18+). Upgrading…"
        curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | sudo -E bash -
        sudo apt-get install -y nodejs
        success "Node.js $(node --version) installed"
    fi
else
    info "Installing Node.js ${NODE_MAJOR}.x from NodeSource…"
    curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | sudo -E bash -
    sudo apt-get install -y nodejs
    success "Node.js $(node --version) installed"
fi

info "npm version : $(npm --version)"

# ── Clone / update repo ───────────────────────────────────────────────────────
step "Setting up application files"
if [[ -d "$INSTALL_DIR/.git" ]]; then
    info "Repository already exists — pulling latest changes…"
    git -C "$INSTALL_DIR" pull origin main || git -C "$INSTALL_DIR" pull origin master || warn "Could not pull — using existing files"
elif [[ -d "$INSTALL_DIR" ]]; then
    info "Directory exists but is not a git repo — using existing files"
else
    info "Cloning repository…"
    git clone "$REPO_URL" "$INSTALL_DIR"
    success "Repository cloned to $INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# ── npm install ───────────────────────────────────────────────────────────────
step "Installing Node.js dependencies"
info "This may take a few minutes on Raspberry Pi (compiling native SQLite)…"
npm install --omit=dev
success "Dependencies installed"

# ── Environment file ──────────────────────────────────────────────────────────
step "Configuring environment"
ENV_FILE="$INSTALL_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
    info ".env already exists — keeping existing configuration"
else
    info "Generating secure JWT secret…"
    JWT_SECRET=$(openssl rand -hex 32)
    cat > "$ENV_FILE" <<EOF
# StockArena environment configuration
# Generated by install.sh on $(date)

PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
NODE_ENV=production
EOF
    success ".env created with random JWT secret"
fi

# ── systemd service ───────────────────────────────────────────────────────────
step "Installing systemd service"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

# Substitute real paths into service template
sudo tee "$SERVICE_FILE" > /dev/null <<EOF
[Unit]
Description=StockArena Stock Trading Game
Documentation=${REPO_URL}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${USER}
WorkingDirectory=${INSTALL_DIR}
ExecStart=$(command -v node) server.js
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

# Load .env variables
EnvironmentFile=-${INSTALL_DIR}/.env

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=${INSTALL_DIR}

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
success "systemd service installed and enabled on boot"

# ── Start / restart service ───────────────────────────────────────────────────
step "Starting StockArena"
if sudo systemctl is-active --quiet "$SERVICE_NAME"; then
    sudo systemctl restart "$SERVICE_NAME"
    success "Service restarted"
else
    sudo systemctl start "$SERVICE_NAME"
    success "Service started"
fi

sleep 2  # give it a moment to bind the port

# ── Firewall (optional, warn only) ───────────────────────────────────────────
if command -v ufw &>/dev/null && sudo ufw status | grep -q "Status: active"; then
    warn "ufw firewall is active. Opening port $PORT…"
    sudo ufw allow "$PORT/tcp" comment "StockArena" 2>/dev/null && success "Port $PORT opened in ufw" || warn "Could not open ufw port — open manually: sudo ufw allow ${PORT}/tcp"
fi

# ── Get local IP ──────────────────────────────────────────────────────────────
LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}')

# ── Done ─────────────────────────────────────────────────────────────────────
echo -e "\n${BOLD}${G}╔══════════════════════════════════════════════════════╗${N}"
echo -e "${BOLD}${G}║  ✅  StockArena is running!                          ║${N}"
echo -e "${BOLD}${G}╠══════════════════════════════════════════════════════╣${N}"
echo -e "${BOLD}${G}║${N}  Local:   ${BOLD}http://localhost:${PORT}${N}"
if [[ -n "$LOCAL_IP" ]]; then
echo -e "${BOLD}${G}║${N}  Network: ${BOLD}http://${LOCAL_IP}:${PORT}${N}"
fi
echo -e "${BOLD}${G}╠══════════════════════════════════════════════════════╣${N}"
echo -e "${BOLD}${G}║${N}  First registration = admin account               ${BOLD}${G}║${N}"
echo -e "${BOLD}${G}║${N}  Logs: sudo journalctl -u ${SERVICE_NAME} -f          ${BOLD}${G}║${N}"
echo -e "${BOLD}${G}║${N}  Stop: sudo systemctl stop ${SERVICE_NAME}            ${BOLD}${G}║${N}"
echo -e "${BOLD}${G}╚══════════════════════════════════════════════════════╝${N}\n"

# ── Useful commands reminder ─────────────────────────────────────────────────
echo -e "${Y}Useful commands:${N}"
echo "  Status  : sudo systemctl status $SERVICE_NAME"
echo "  Logs    : sudo journalctl -u $SERVICE_NAME -f"
echo "  Restart : sudo systemctl restart $SERVICE_NAME"
echo "  Stop    : sudo systemctl stop $SERVICE_NAME"
echo "  Update  : cd $INSTALL_DIR && git pull && npm install --omit=dev && sudo systemctl restart $SERVICE_NAME"
echo ""
